name = "gmail-telegram-notifier"
main = "src/index.ts"
compatibility_date = "2023-05-18"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


[[kv_namespaces]]
binding = "telegram-gmail"
id = "024fa247c98b49efa73fb8aaa8bc21b9"

# Scheduled job to check emails periodically (as backup for push notifications)
[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes

[vars]
TELEGRAM_BOT_USERNAME = "mygmailsbot"
GOOGLE_CLIENT_ID = "1084242177961-7fsaufibk1ttjmiikvcmmsrstoi10jka.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = "https://gmail-telegram-notifier.masihjahan.workers.dev/auth/google/callback"

# Secrets that should be set using wrangler secret put
# note: WEBHOOK_SECRET is a random string, so you can generate it by running this command: openssl rand -base64 32

# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put WEBHOOK_SECRET
# wrangler secret put GOOGLE_CLIENT_SECRET